################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/ti/access.c \
../src/ti/api.c \
../src/ti/archfile.c \
../src/ti/archive.c \
../src/ti/args.c \
../src/ti/auth.c \
../src/ti/away.c \
../src/ti/backup.c \
../src/ti/backups.c \
../src/ti/build.c \
../src/ti/cfg.c \
../src/ti/clients.c \
../src/ti/closure.c \
../src/ti/collection.c \
../src/ti/collections.c \
../src/ti/connect.c \
../src/ti/counters.c \
../src/ti/data.c \
../src/ti/do.c \
../src/ti/epkg.c \
../src/ti/evars.c \
../src/ti/event.c \
../src/ti/events.c \
../src/ti/field.c \
../src/ti/fwd.c \
../src/ti/index.c \
../src/ti/job.c \
../src/ti/mapping.c \
../src/ti/name.c \
../src/ti/names.c \
../src/ti/ncache.c \
../src/ti/nil.c \
../src/ti/node.c \
../src/ti/nodes.c \
../src/ti/opr.c \
../src/ti/pipe.c \
../src/ti/pkg.c \
../src/ti/procedure.c \
../src/ti/procedures.c \
../src/ti/prom.c \
../src/ti/prop.c \
../src/ti/proto.c \
../src/ti/qbind.c \
../src/ti/query.c \
../src/ti/quorum.c \
../src/ti/raw.c \
../src/ti/regex.c \
../src/ti/req.c \
../src/ti/restore.c \
../src/ti/rjob.c \
../src/ti/rpkg.c \
../src/ti/scope.c \
../src/ti/signals.c \
../src/ti/spec.c \
../src/ti/store.c \
../src/ti/stream.c \
../src/ti/sync.c \
../src/ti/syncarchive.c \
../src/ti/syncer.c \
../src/ti/syncevents.c \
../src/ti/syncfull.c \
../src/ti/task.c \
../src/ti/tcp.c \
../src/ti/template.c \
../src/ti/thing.c \
../src/ti/things.c \
../src/ti/token.c \
../src/ti/type.c \
../src/ti/types.c \
../src/ti/user.c \
../src/ti/users.c \
../src/ti/val.c \
../src/ti/varr.c \
../src/ti/vbool.c \
../src/ti/verror.c \
../src/ti/version.c \
../src/ti/vfloat.c \
../src/ti/vint.c \
../src/ti/vset.c \
../src/ti/wareq.c \
../src/ti/watch.c \
../src/ti/web.c \
../src/ti/wrap.c \
../src/ti/write.c 

OBJS += \
./src/ti/access.o \
./src/ti/api.o \
./src/ti/archfile.o \
./src/ti/archive.o \
./src/ti/args.o \
./src/ti/auth.o \
./src/ti/away.o \
./src/ti/backup.o \
./src/ti/backups.o \
./src/ti/build.o \
./src/ti/cfg.o \
./src/ti/clients.o \
./src/ti/closure.o \
./src/ti/collection.o \
./src/ti/collections.o \
./src/ti/connect.o \
./src/ti/counters.o \
./src/ti/data.o \
./src/ti/do.o \
./src/ti/epkg.o \
./src/ti/evars.o \
./src/ti/event.o \
./src/ti/events.o \
./src/ti/field.o \
./src/ti/fwd.o \
./src/ti/index.o \
./src/ti/job.o \
./src/ti/mapping.o \
./src/ti/name.o \
./src/ti/names.o \
./src/ti/ncache.o \
./src/ti/nil.o \
./src/ti/node.o \
./src/ti/nodes.o \
./src/ti/opr.o \
./src/ti/pipe.o \
./src/ti/pkg.o \
./src/ti/procedure.o \
./src/ti/procedures.o \
./src/ti/prom.o \
./src/ti/prop.o \
./src/ti/proto.o \
./src/ti/qbind.o \
./src/ti/query.o \
./src/ti/quorum.o \
./src/ti/raw.o \
./src/ti/regex.o \
./src/ti/req.o \
./src/ti/restore.o \
./src/ti/rjob.o \
./src/ti/rpkg.o \
./src/ti/scope.o \
./src/ti/signals.o \
./src/ti/spec.o \
./src/ti/store.o \
./src/ti/stream.o \
./src/ti/sync.o \
./src/ti/syncarchive.o \
./src/ti/syncer.o \
./src/ti/syncevents.o \
./src/ti/syncfull.o \
./src/ti/task.o \
./src/ti/tcp.o \
./src/ti/template.o \
./src/ti/thing.o \
./src/ti/things.o \
./src/ti/token.o \
./src/ti/type.o \
./src/ti/types.o \
./src/ti/user.o \
./src/ti/users.o \
./src/ti/val.o \
./src/ti/varr.o \
./src/ti/vbool.o \
./src/ti/verror.o \
./src/ti/version.o \
./src/ti/vfloat.o \
./src/ti/vint.o \
./src/ti/vset.o \
./src/ti/wareq.o \
./src/ti/watch.o \
./src/ti/web.o \
./src/ti/wrap.o \
./src/ti/write.o 

C_DEPS += \
./src/ti/access.d \
./src/ti/api.d \
./src/ti/archfile.d \
./src/ti/archive.d \
./src/ti/args.d \
./src/ti/auth.d \
./src/ti/away.d \
./src/ti/backup.d \
./src/ti/backups.d \
./src/ti/build.d \
./src/ti/cfg.d \
./src/ti/clients.d \
./src/ti/closure.d \
./src/ti/collection.d \
./src/ti/collections.d \
./src/ti/connect.d \
./src/ti/counters.d \
./src/ti/data.d \
./src/ti/do.d \
./src/ti/epkg.d \
./src/ti/evars.d \
./src/ti/event.d \
./src/ti/events.d \
./src/ti/field.d \
./src/ti/fwd.d \
./src/ti/index.d \
./src/ti/job.d \
./src/ti/mapping.d \
./src/ti/name.d \
./src/ti/names.d \
./src/ti/ncache.d \
./src/ti/nil.d \
./src/ti/node.d \
./src/ti/nodes.d \
./src/ti/opr.d \
./src/ti/pipe.d \
./src/ti/pkg.d \
./src/ti/procedure.d \
./src/ti/procedures.d \
./src/ti/prom.d \
./src/ti/prop.d \
./src/ti/proto.d \
./src/ti/qbind.d \
./src/ti/query.d \
./src/ti/quorum.d \
./src/ti/raw.d \
./src/ti/regex.d \
./src/ti/req.d \
./src/ti/restore.d \
./src/ti/rjob.d \
./src/ti/rpkg.d \
./src/ti/scope.d \
./src/ti/signals.d \
./src/ti/spec.d \
./src/ti/store.d \
./src/ti/stream.d \
./src/ti/sync.d \
./src/ti/syncarchive.d \
./src/ti/syncer.d \
./src/ti/syncevents.d \
./src/ti/syncfull.d \
./src/ti/task.d \
./src/ti/tcp.d \
./src/ti/template.d \
./src/ti/thing.d \
./src/ti/things.d \
./src/ti/token.d \
./src/ti/type.d \
./src/ti/types.d \
./src/ti/user.d \
./src/ti/users.d \
./src/ti/val.d \
./src/ti/varr.d \
./src/ti/vbool.d \
./src/ti/verror.d \
./src/ti/version.d \
./src/ti/vfloat.d \
./src/ti/vint.d \
./src/ti/vset.d \
./src/ti/wareq.d \
./src/ti/watch.d \
./src/ti/web.d \
./src/ti/wrap.d \
./src/ti/write.d 


# Each subdirectory must supply rules for building sources it contributes
src/ti/%.o: ../src/ti/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -std=gnu11 -I../inc -O0 -g3 -Wall -Wextra -c -fmessage-length=0 -march=native -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


