################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/ti/access.c \
../src/ti/api.c \
../src/ti/archfile.c \
../src/ti/archive.c \
../src/ti/args.c \
../src/ti/async.c \
../src/ti/auth.c \
../src/ti/away.c \
../src/ti/backup.c \
../src/ti/backups.c \
../src/ti/build.c \
../src/ti/cfg.c \
../src/ti/change.c \
../src/ti/changes.c \
../src/ti/clients.c \
../src/ti/closure.c \
../src/ti/collection.c \
../src/ti/collections.c \
../src/ti/condition.c \
../src/ti/connect.c \
../src/ti/counters.c \
../src/ti/cpkg.c \
../src/ti/ctask.c \
../src/ti/datetime.c \
../src/ti/deep.c \
../src/ti/do.c \
../src/ti/dump.c \
../src/ti/enum.c \
../src/ti/enums.c \
../src/ti/evars.c \
../src/ti/export.c \
../src/ti/field.c \
../src/ti/flags.c \
../src/ti/fmt.c \
../src/ti/fn.c \
../src/ti/forloop.c \
../src/ti/future.c \
../src/ti/fwd.c \
../src/ti/gc.c \
../src/ti/index.c \
../src/ti/item.c \
../src/ti/mapping.c \
../src/ti/member.c \
../src/ti/method.c \
../src/ti/module.c \
../src/ti/modules.c \
../src/ti/name.c \
../src/ti/names.c \
../src/ti/ncache.c \
../src/ti/nil.c \
../src/ti/node.c \
../src/ti/nodes.c \
../src/ti/opr.c \
../src/ti/pipe.c \
../src/ti/pkg.c \
../src/ti/preopr.c \
../src/ti/proc.c \
../src/ti/procedure.c \
../src/ti/procedures.c \
../src/ti/prop.c \
../src/ti/proto.c \
../src/ti/qbind.c \
../src/ti/qcache.c \
../src/ti/query.c \
../src/ti/quorum.c \
../src/ti/raw.c \
../src/ti/regex.c \
../src/ti/req.c \
../src/ti/restore.c \
../src/ti/room.c \
../src/ti/rooms.c \
../src/ti/rpkg.c \
../src/ti/scope.c \
../src/ti/signals.c \
../src/ti/spec.c \
../src/ti/store.c \
../src/ti/stream.c \
../src/ti/sync.c \
../src/ti/syncarchive.c \
../src/ti/syncer.c \
../src/ti/syncevents.c \
../src/ti/syncfull.c \
../src/ti/task.c \
../src/ti/tasks.c \
../src/ti/tcp.c \
../src/ti/template.c \
../src/ti/thing.c \
../src/ti/things.c \
../src/ti/token.c \
../src/ti/ttask.c \
../src/ti/type.c \
../src/ti/types.c \
../src/ti/tz.c \
../src/ti/user.c \
../src/ti/users.c \
../src/ti/val.c \
../src/ti/varr.c \
../src/ti/vbool.c \
../src/ti/verror.c \
../src/ti/version.c \
../src/ti/vfloat.c \
../src/ti/vint.c \
../src/ti/vset.c \
../src/ti/vtask.c \
../src/ti/warn.c \
../src/ti/watch.c \
../src/ti/web.c \
../src/ti/wrap.c \
../src/ti/write.c \
../src/ti/ws.c 

OBJS += \
./src/ti/access.o \
./src/ti/api.o \
./src/ti/archfile.o \
./src/ti/archive.o \
./src/ti/args.o \
./src/ti/async.o \
./src/ti/auth.o \
./src/ti/away.o \
./src/ti/backup.o \
./src/ti/backups.o \
./src/ti/build.o \
./src/ti/cfg.o \
./src/ti/change.o \
./src/ti/changes.o \
./src/ti/clients.o \
./src/ti/closure.o \
./src/ti/collection.o \
./src/ti/collections.o \
./src/ti/condition.o \
./src/ti/connect.o \
./src/ti/counters.o \
./src/ti/cpkg.o \
./src/ti/ctask.o \
./src/ti/datetime.o \
./src/ti/deep.o \
./src/ti/do.o \
./src/ti/dump.o \
./src/ti/enum.o \
./src/ti/enums.o \
./src/ti/evars.o \
./src/ti/export.o \
./src/ti/field.o \
./src/ti/flags.o \
./src/ti/fmt.o \
./src/ti/fn.o \
./src/ti/forloop.o \
./src/ti/future.o \
./src/ti/fwd.o \
./src/ti/gc.o \
./src/ti/index.o \
./src/ti/item.o \
./src/ti/mapping.o \
./src/ti/member.o \
./src/ti/method.o \
./src/ti/module.o \
./src/ti/modules.o \
./src/ti/name.o \
./src/ti/names.o \
./src/ti/ncache.o \
./src/ti/nil.o \
./src/ti/node.o \
./src/ti/nodes.o \
./src/ti/opr.o \
./src/ti/pipe.o \
./src/ti/pkg.o \
./src/ti/preopr.o \
./src/ti/proc.o \
./src/ti/procedure.o \
./src/ti/procedures.o \
./src/ti/prop.o \
./src/ti/proto.o \
./src/ti/qbind.o \
./src/ti/qcache.o \
./src/ti/query.o \
./src/ti/quorum.o \
./src/ti/raw.o \
./src/ti/regex.o \
./src/ti/req.o \
./src/ti/restore.o \
./src/ti/room.o \
./src/ti/rooms.o \
./src/ti/rpkg.o \
./src/ti/scope.o \
./src/ti/signals.o \
./src/ti/spec.o \
./src/ti/store.o \
./src/ti/stream.o \
./src/ti/sync.o \
./src/ti/syncarchive.o \
./src/ti/syncer.o \
./src/ti/syncevents.o \
./src/ti/syncfull.o \
./src/ti/task.o \
./src/ti/tasks.o \
./src/ti/tcp.o \
./src/ti/template.o \
./src/ti/thing.o \
./src/ti/things.o \
./src/ti/token.o \
./src/ti/ttask.o \
./src/ti/type.o \
./src/ti/types.o \
./src/ti/tz.o \
./src/ti/user.o \
./src/ti/users.o \
./src/ti/val.o \
./src/ti/varr.o \
./src/ti/vbool.o \
./src/ti/verror.o \
./src/ti/version.o \
./src/ti/vfloat.o \
./src/ti/vint.o \
./src/ti/vset.o \
./src/ti/vtask.o \
./src/ti/warn.o \
./src/ti/watch.o \
./src/ti/web.o \
./src/ti/wrap.o \
./src/ti/write.o \
./src/ti/ws.o 

C_DEPS += \
./src/ti/access.d \
./src/ti/api.d \
./src/ti/archfile.d \
./src/ti/archive.d \
./src/ti/args.d \
./src/ti/async.d \
./src/ti/auth.d \
./src/ti/away.d \
./src/ti/backup.d \
./src/ti/backups.d \
./src/ti/build.d \
./src/ti/cfg.d \
./src/ti/change.d \
./src/ti/changes.d \
./src/ti/clients.d \
./src/ti/closure.d \
./src/ti/collection.d \
./src/ti/collections.d \
./src/ti/condition.d \
./src/ti/connect.d \
./src/ti/counters.d \
./src/ti/cpkg.d \
./src/ti/ctask.d \
./src/ti/datetime.d \
./src/ti/deep.d \
./src/ti/do.d \
./src/ti/dump.d \
./src/ti/enum.d \
./src/ti/enums.d \
./src/ti/evars.d \
./src/ti/export.d \
./src/ti/field.d \
./src/ti/flags.d \
./src/ti/fmt.d \
./src/ti/fn.d \
./src/ti/forloop.d \
./src/ti/future.d \
./src/ti/fwd.d \
./src/ti/gc.d \
./src/ti/index.d \
./src/ti/item.d \
./src/ti/mapping.d \
./src/ti/member.d \
./src/ti/method.d \
./src/ti/module.d \
./src/ti/modules.d \
./src/ti/name.d \
./src/ti/names.d \
./src/ti/ncache.d \
./src/ti/nil.d \
./src/ti/node.d \
./src/ti/nodes.d \
./src/ti/opr.d \
./src/ti/pipe.d \
./src/ti/pkg.d \
./src/ti/preopr.d \
./src/ti/proc.d \
./src/ti/procedure.d \
./src/ti/procedures.d \
./src/ti/prop.d \
./src/ti/proto.d \
./src/ti/qbind.d \
./src/ti/qcache.d \
./src/ti/query.d \
./src/ti/quorum.d \
./src/ti/raw.d \
./src/ti/regex.d \
./src/ti/req.d \
./src/ti/restore.d \
./src/ti/room.d \
./src/ti/rooms.d \
./src/ti/rpkg.d \
./src/ti/scope.d \
./src/ti/signals.d \
./src/ti/spec.d \
./src/ti/store.d \
./src/ti/stream.d \
./src/ti/sync.d \
./src/ti/syncarchive.d \
./src/ti/syncer.d \
./src/ti/syncevents.d \
./src/ti/syncfull.d \
./src/ti/task.d \
./src/ti/tasks.d \
./src/ti/tcp.d \
./src/ti/template.d \
./src/ti/thing.d \
./src/ti/things.d \
./src/ti/token.d \
./src/ti/ttask.d \
./src/ti/type.d \
./src/ti/types.d \
./src/ti/tz.d \
./src/ti/user.d \
./src/ti/users.d \
./src/ti/val.d \
./src/ti/varr.d \
./src/ti/vbool.d \
./src/ti/verror.d \
./src/ti/version.d \
./src/ti/vfloat.d \
./src/ti/vint.d \
./src/ti/vset.d \
./src/ti/vtask.d \
./src/ti/warn.d \
./src/ti/watch.d \
./src/ti/web.d \
./src/ti/wrap.d \
./src/ti/write.d \
./src/ti/ws.d 


# Each subdirectory must supply rules for building sources it contributes
src/ti/%.o: ../src/ti/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -std=gnu11 -DLWS_WITH_LIBUV=1 -DLWS_WITH_PLUGINS=1 -I../inc -O0 -g3 -Wall -Wextra -c -fmessage-length=0 -march=native -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


