/*
 * langdef.h
 *
 * This grammar is generated using the Grammar.export_c() method and
 * should be used with the libcleri module.
 *
 * Source class: LangDef
 * Created at: 2024-02-11 20:55:25
 */
#ifndef CLERI_EXPORT_LANGDEF_H_
#define CLERI_EXPORT_LANGDEF_H_

#include <cleri/cleri.h>

cleri_grammar_t * compile_langdef(void);

/* TODO: (COMPAT) For compatibility with < v1.5 (old syntax) */
cleri_grammar_t * compile_compat(void);

enum cleri_grammar_ids {
    CLERI_NONE,   // used for objects with no name
    CLERI_GID_ARRAY,
    CLERI_GID_ASSIGN,
    CLERI_GID_BLOCK,
    CLERI_GID_CHAIN,
    CLERI_GID_CLOSURE,
    CLERI_GID_ENUM_,
    CLERI_GID_EXPRESSION,
    CLERI_GID_FOR_STATEMENT,
    CLERI_GID_FUNCTION,
    CLERI_GID_IF_STATEMENT,
    CLERI_GID_INDEX,
    CLERI_GID_INSTANCE,
    CLERI_GID_K_BREAK,
    CLERI_GID_K_CONTINUE,
    CLERI_GID_K_ELSE,
    CLERI_GID_K_FOR,
    CLERI_GID_K_IF,
    CLERI_GID_K_IN,
    CLERI_GID_K_RETURN,
    CLERI_GID_NAME,
    CLERI_GID_NAME_OPT_MORE,
    CLERI_GID_OPERATIONS,
    CLERI_GID_OPR0_MUL_DIV_MOD,
    CLERI_GID_OPR1_ADD_SUB,
    CLERI_GID_OPR2_BITWISE_SHIFT,
    CLERI_GID_OPR3_BITWISE_AND,
    CLERI_GID_OPR4_BITWISE_XOR,
    CLERI_GID_OPR5_BITWISE_OR,
    CLERI_GID_OPR6_COMPARE,
    CLERI_GID_OPR7_CMP_AND,
    CLERI_GID_OPR8_CMP_OR,
    CLERI_GID_OPR9_TERNARY,
    CLERI_GID_PARENTHESIS,
    CLERI_GID_RETURN_STATEMENT,
    CLERI_GID_SLICE,
    CLERI_GID_START,
    CLERI_GID_STATEMENT,
    CLERI_GID_TEMPLATE,
    CLERI_GID_THING,
    CLERI_GID_T_FALSE,
    CLERI_GID_T_FLOAT,
    CLERI_GID_T_INT,
    CLERI_GID_T_NIL,
    CLERI_GID_T_REGEX,
    CLERI_GID_T_STRING,
    CLERI_GID_T_TRUE,
    CLERI_GID_VAR,
    CLERI_GID_VAR_OPT_MORE,
    CLERI_GID_X_ARRAY,
    CLERI_GID_X_ASSIGN,
    CLERI_GID_X_BLOCK,
    CLERI_GID_X_CHAIN,
    CLERI_GID_X_CLOSURE,
    CLERI_GID_X_FUNCTION,
    CLERI_GID_X_INDEX,
    CLERI_GID_X_PARENTHESIS,
    CLERI_GID_X_PREOPR,
    CLERI_GID_X_TEMPLATE,
    CLERI_GID_X_TERNARY,
    CLERI_GID_X_THING,
    CLERI_END // can be used to get the enum length
};

#endif /* CLERI_EXPORT_LANGDEF_H_ */

